import { getDate } from "src/common/utils";

export const htmlBlankPage = ( bgImg: any, logoImg: any): string => {
  const { currentYear } = getDate()

  return `
  <html lang="es">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>PDF Cotizacion Template</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          color: #000;
        }

        .bg {
          width: 100%;
          height: 100%;
          position: fixed;
          top: 0px;
          right: 0px;
          bottom: 0px;
          left: 0px;
          z-index: -1;
        }

        .pdf-container {
          position: absolute;
          margin-right: 60px;
          margin-left: 60px;
          width: calc(100% - 120px);
          height: 100%;
          top: 0px;
          right: 0px;
          bottom: 0px;
          left: 0px;
          z-index: 10;
        }

        .header {
          width: 100%;
          margin-top: 65.5px;
          display: flex;
          align-items: center;
          gap: 8px
        }

        .date-container {
          width: 100%;
          display: flex;
          flex-direction: column;
        }
        .date {
          width: 100%;
          text-align: end;
          font-weight: bold;
          box-sizing:
          border-box;
          font-size: 18px;
        }

        .cliente {
          width: 100%;
          margin-top: 40px;
          display: flex;
          flex-direction: column;
          font-size: 16px;
        }

        .data {
          width: 100%;
          margin-top: 40px;
          display: flex;
          flex-direction: column;
          font-size: 12px;
          font-weight: bold;
        }

        .table {
          width: 100%;
          margin-top: 14px;
          display: flex;
          flex-direction: column;
          border: 1px solid #000;
          background-color: transparent;
        }
        .table-row {
          width: 100%;
          display: flex;
          font-size: 10px;
          font-weight: bold;
        }
        .table-cell-header {
          border: 1px solid #000;
          display: flex;
          justify-content: center;
          align-items: center;
          flex-direction: column;
          padding: 0 2px;
        }
        .table-cell-body {
          border: 1px solid #000;
          display: flex;
          flex-direction: column;
          font-size: 11px;
          padding: 1px 2px;
        }

        .payment {
          display: flex;
        }

        .footer {
          text-align: end;
          position: absolute;
          font-weight: bold;
          font-size: 12px;
          bottom: 15px;
          left: 0;
          right: 60;
        }
      </style>
    </head>

    <body style="position: relative">

      <div class="bg">
        <img src="data:image/svg+xml;base64, ${bgImg}" alt="background-template" style="width: 100%; height: 100%; object-fit: cover; position: absolute; top: 0; left: 0;" />
      </div>

      <div class="pdf-container">
        <div class="header">
          <div style="display: flex; gap: 8px">
            <img src="data:image/jpeg;base64, ${logoImg}" alt="constroad-logo" style="width: 40px; height: 40px; border-radius: 10px;" />
            <div style="font-size: 32px;" >ConstRoad</div>
          </div>
          <div class="date-container">
          </div>
        </div>
      </div>

      <div class="footer">
        <p style='font-size: 10px;'>Generated by ConstRoad - ${currentYear}</p>
      </div>

    </body>
  </html>
  `;
}

